services:
  bot:
    image: it-reserved-bot:latest
    env_file:
      - ./bot/.env
    network_mode: host
    environment:
      - IN_DOCKER=true
      - HTTP_PROXY=
      - HTTPS_PROXY=
      - http_proxy=
      - https_proxy=
      - NO_PROXY=localhost,127.0.0.1
      - no_proxy=localhost,127.0.0.1
      - TG_SOCKS=socks5://127.0.0.1:1080
    restart: unless-stopped
    volumes:
      - ./bot/src:/app/src
      - ./bot/data:/app/data
    shm_size: 1gb
