services:
  bot:
    image: it-reserved-bot:latest
    env_file:
      - ./bot/.env
    network_mode: host
    environment:
      - IN_DOCKER=true
      - HTTP_PROXY=http://127.0.0.1:1087
      - HTTPS_PROXY=http://127.0.0.1:1087
      - http_proxy=http://127.0.0.1:1087
      - https_proxy=http://127.0.0.1:1087
      - NO_PROXY=localhost,127.0.0.1,vpbx.mts.ru
      - no_proxy=localhost,127.0.0.1,vpbx.mts.ru
    restart: unless-stopped
    volumes:
      - ./bot/src:/app/src
      - ./bot/data:/app/data
    shm_size: 1gb
