services:
  bot:
    image: it-reserved-bot:latest
    env_file:
      - ./bot/.env
    network_mode: host
    environment:
      - IN_DOCKER=true
      - NO_PROXY=localhost,127.0.0.1
      - no_proxy=localhost,127.0.0.1
      - TG_PROXY=http://127.0.0.1:1087
    restart: unless-stopped
    volumes:
      - ./bot/src:/app/src
      - ./bot/data:/app/data
    shm_size: 1gb
